spring:
  application:
    name: workload-service
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:workload_db
    username: sa
    password:
    driver-class-name: org.h2.Driver

server:
  port: 8082

jwt:
  secret:
    key: "2dae84f846e4f4b158a8d26681707f4338495bc7ab68151d7f7679cc5e56202dd3da0d356da007a7c28cb0b780418f4f3246769972d6feaa8f610c7d1e7ecf6a"
  expiration:
    time: 86400000 #1 day
