spring:
  application:
    name: workload-service
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false # don't requeue rejected messages
  data:
    mongodb:
      auto-index-creation: true

jwt:
  secret:
    key: "2dae84f846e4f4b158a8d26681707f4338495bc7ab68151d7f7679cc5e56202dd3da0d356da007a7c28cb0b780418f4f3246769972d6feaa8f610c7d1e7ecf6a"
  expiration:
    time: 86400000 #1 day
